apiVersion: batch/v1
kind: Job
metadata:
  name: presync-echo
  namespace: web
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: echo
        image: busybox:1.36
        command: ["sh","-c","echo 'PreSync: starting sync' && sleep 2"]
